### ISSUE TITLE
Define diagram of runtime components

### ISSUE THREAD

**Issue by SaraElBrak** [amosproj/amos2023ss03-qachat#10]
## User story
1. As a Product Owner
2. I want to outline the elements of the diagram, for example nodes (e.g., servers), components (e.g., web servers, application servers), connections (e.g., network links, message queues), triggers, outputs, ...
3. So that different stakeholders understand the product's deployment architecture and how it is configured to operate.

## Acceptance criteria
* Clarity: The diagram should be easy to understand and not cluttered with unnecessary details.
* Completeness: The diagram should include all the necessary components and their relationships in the system. It should accurately represent the physical architecture of the product, including hardware devices, servers, databases, and other software components.
* Scalability: The diagram should be scalable to accommodate future growth of the product. 
* Consistency: The diagram should be consistent with the actual deployment architecture of the product.
* Security: The diagram should take into account security concerns and highlight potential security risks in the product's architecture. 
* Readability: The diagram should be readable and visually appealing. 
* Usefulness: The diagram should serve the defined purpose for the final users. It should provide insight into the physical architecture of the product and facilitate communication between team members.

## Definition of done (DoD)
* one-page documentation is uploaded in the Documentation folder
* useful sources :
https://plantuml.com/en/component-diagram
https://www.visual-paradigm.com/features/uml-tool/    (view the components diagram)
https://www.youtube.com/watch?v=VIqJ4rdKUEY
https://www.youtube.com/watch?v=uJez6Nd8IRI
https://www.youtube.com/watch?v=n5eDzJpIY4Y

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by emuguy1** [comment]
The API´s(GoogleDrive and Confluence need to be outside the server of course : D

**Comment by emuguy1** [comment]
There are multiple parts:
1. The DataProcessing Component takes the data from the Data-Source-API's and builds the vectors that then get saved to the Vectore Store
2. The SlackAPI Sends the query from the user to our Slackbot, which then distributes the query to our LLM and the Similarity Search Component. The Similarity Search Component looks for Similiarities in the vectore store and sends relevant vectors to the Data Processing Component. The Data Processing Component then gets the respective files or textual representations from the APIs and send the data to the LLM(-Server) This process everything and sends the Answer to the Bot which sends it via the Slack-API to the User

**Comment by tkonheiser** [comment]
It would be great, if you could add reading data from PDFs and a translating service API interface (Sebastian will probably provide us with a deepl.com Pro API Key).

**Comment by emuguy1** [comment]
We thought this would be inside the Data Processing But maybe the translation thing is a good idea

**Comment by Kadi-7** [comment]
I find the diagram pretty good but there is a thing with Langchain. As I understand from some tutorial that Langchain does the similarity search, vectors store (depending on other service) and the interacting with the LLM Model.

**Comment by Kadi-7** [comment]
Here the updated diagram 

[runtime_component.pdf](https://github.com/amosproj/amos2023ss03-qachat/files/11361957/runtime_component.pdf)

and the file of draw.io can be found here: https://github.com/amosproj/amos2023ss03-qachat/blob/main/Documentation/Diagrams/tuntime_component.drawio
