### ISSUE TITLE
check conformity with NDA

### ISSUE THREAD

**Issue by SaraElBrak** [amosproj/amos2023ss03-qachat#107]
## User story
1. As a project team
2. We need to ensure that all services are compatible with the NDA
3. So that the solution developed aligns with the customer's security guidelines.

## Acceptance criteria
* Verify that our services are compatible with the NDA.

## Definition of done (DoD)
* Acceptance criteria are met.
* Work products are uploaded to the Github repository.
* A pull request is created for each related branch.
* The work products in the pull requests are reviewed.
* The corresponding branches are merged and closed.
* The bill of materials section of the planning documents is updated.
* All defined conventions are complied with.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by emuguy1** [comment]
Email for written allowence for the usage with our services is written. Checked how didnt yet receive the nda and who signed it to have a detailed knowledge on furtger steps.
