### ISSUE TITLE
create a message indicating the processing of the Slackbot

### ISSUE THREAD

**Issue by SaraElBrak** [amosproj/amos2023ss03-qachat#109]
## User story
1. As an admin
2. I want to inform the user that the Slackbot is processing
3. So that the user experience is improved

## Acceptance criteria
* The message should inform the user that the processing is happening. 
* The message must be removed once the final response is sent.

## Definition of done (DoD)
* Acceptance criteria are met.
* Work products are uploaded to the Github repository.
* A pull request is created for each related branch.
* The work products in the pull requests are reviewed.
* The corresponding branches are merged and closed.
* The bill of materials section of the planning documents is updated.
* All defined conventions are complied with.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by tkonheiser** [comment]
duplicate
