### ISSUE TITLE
split up long text block for database

### ISSUE THREAD

**Issue by SaraElBrak** [amosproj/amos2023ss03-qachat#110]
## User story
1. As a software developer
2. I need to split up long text blocks for storage in a database
3. So that the database performance and scalability are improved, and the searchability process is more precise.

## Acceptance criteria
* Develop a mechanism that splits the long text blocks into smaller segments.
* Verify that the splitting mechanism correctly identifies and sets appropriate boundaries for the segments.
* Document the splitting mechanism.

## Definition of done (DoD)
* Acceptance criteria are met.
* Work products are uploaded to the Github repository.
* A pull request is created for each related branch.
* The work products in the pull requests are reviewed.
* The corresponding branches are merged and closed.
* The bill of materials section of the planning documents is updated.
* All defined conventions are complied with.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by emuguy1** [comment]
Stuff to do:

- [ ] Annotate message with username
- [ ] Change id to channel plus message id
- [ ] Think about Chunk ids in database
- [ ] Where to chunk

**Comment by zenzeii** [comment]
I see good progress :)

there is only one minor thing that came to attention while doing another issue (read confluence data).

without transform_text_to_chunks it looks like this:


![Image](https://github.com/amosproj/amos2023ss03-qachat/assets/37368423/97c81401-5982-471c-af0d-62c7ee3e88fd)


with transform_text_to_chunks it looks like this:


![Image](https://github.com/amosproj/amos2023ss03-qachat/assets/37368423/9075346a-1863-44b4-835a-64697f4cf741)

Hope this helps to fix the issue :)

**Comment by zenzeii** [comment]
Thanks for the quick fix :)
