### ISSUE TITLE
clean up the repository

### ISSUE THREAD

**Issue by SaraElBrak** [amosproj/amos2023ss03-qachat#113]
## User story
1. As a project team
2. I want / need to update and organize the repository 
3. So that concise and clear documentation is maintained.

## Acceptance criteria
* Update the Bills of Materials in the Planning Documents.
* Check the dependencies and ensure that the requirements file is complete.
* Update documentation: update and ensure that the design documentation accurately reflect the current state of the project.
* Refactor and improve code quality: identify areas where code can be refactored for improved readability, maintainability, and performance. Apply coding standards and removing any code smells or unnecessary complexities.

## Definition of done (DoD)
* Acceptance criteria are met.
* Work products are uploaded to the Github repository.
* A pull request is created for each related branch.
* The work products in the pull requests are reviewed.
* The corresponding branches are merged and closed.
* The bill of materials section of the planning documents is updated.
* All defined conventions are complied with.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by zenzeii** [comment]
Updated the bill of materials with context. Feel free to add if something is missed.
