### ISSUE TITLE
read real data from Slack

### ISSUE THREAD

**Issue by tkonheiser** [amosproj/amos2023ss03-qachat#126]
## User story
1. As a project team
2. We need to read data from the QAware Slack in the database
3. So that experience with real data can be collected and tests with real data can be performed

## Acceptance criteria
* representative data from Slack is collected
* dummy data is removed from the database
* real data is read into the database

## Definition of done (DoD)
* Acceptance criteria are met.
* Work products are uploaded to the Github repository.
* A pull request is created for each related branch.
* The work products in the pull requests are reviewed.
* The corresponding branches are merged and closed.
* The bill of materials section of the planning documents is updated.
* All defined conventions are complied with.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by emuguy1** [comment]
Blocked because of missing access rights. Slack-Admin is contacted.
