### ISSUE TITLE
create the demo day video

### ISSUE THREAD

**Issue by tkonheiser** [amosproj/amos2023ss03-qachat#151]
## User story
1. As a project team
2. We need a demo day video
3. So that our project can be presented on the demo day

## Acceptance criteria
* a 3 minute video is created
* video is approved by QAWare, if QAWare information is included
* the demo day presentation slides are finalized
* the video contains the demo day presentation slides
* the video contains a demo of the software
* the video is narrated
* the video uses a common codec
* the video is uploaded to the Deliverables folder (sprint-12/demo-day-video.mkv)

## Definition of done (DoD)
* Acceptance criteria are met.
* Work products are uploaded to the Github repository.
* A pull request is created for each related branch.
* The work products in the pull requests are reviewed.
* The corresponding branches are merged and closed.
* The bill of materials section of the planning documents is updated.
* All defined conventions are complied with.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by zenzeii** [comment]
https://github.com/amosproj/amos2023ss03-qachat/blob/main/Deliverables/sprint-12/demo-day-video.mkv
