### ISSUE TITLE
implement T5 LLM prototype

### ISSUE THREAD

**Issue by tkonheiser** [amosproj/amos2023ss03-qachat#46]
## User story
1. As a project team
2. I want / need to implement the first draft of the T5 LLM
3. So that we can evaluate the functionality of this LLM and discover problems with this LLM.

## Acceptance criteria
* one or more source code files for the T5 LLM are created
* a separate folder for the T5 LLM source code is created
* the code framework is created according to the defined software architecture
* the LLM framework is compatible with the LLM-Server framework
* source code compiles without errors

## Definition of done (DoD)
* source code is uploaded
* the bill of materials section of the planning documents is updated

## Notes
* [T5 LLM](https://github.com/amosproj/amos2023ss03-qachat/blob/main/Documentation/LLM-Research/LLM-Models.md#flan---opensource-llm-by-google)

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by zenzeii** [comment]
Source code and readme are uploaded here: https://github.com/amosproj/amos2023ss03-qachat/tree/main/QAChat/LLM_Prototypes/T5


We were able to run like this:
![Image](https://github.com/amosproj/amos2023ss03-qachat/assets/37368423/485b3ebb-05fe-4173-9f1c-745f161d5887)


But because of a problem from hugginface side we are not able to run again:
![Image](https://github.com/amosproj/amos2023ss03-qachat/assets/37368423/d71f2b98-f987-41bc-8cbf-4f6f39861010)

**Comment by Kadi-7** [comment]
Regarding the creation of sentence embeddings from T5, unlike BERT, T5 does not have a CLS token and returns multiple outputs. 
To obtain the embeddings, there are three possible methods: (i) using the representation of the first token in the encoder, (ii) taking the average of all token representations from the encoder, and (iii) using the representation of the first token in the decoder.
Recently, Google has introduced ST5 (Sentence T5), which is a tool for generating sentence embeddings and can be found at:  https://tfhub.dev/google/collections/sentence-t5.
Additional details can be found at: https://arxiv.org/abs/2108.08877
