### ISSUE TITLE
research Slack bot requirements

### ISSUE THREAD

**Issue by tkonheiser** [amosproj/amos2023ss03-qachat#5]
## User story
1. As a Product Owner
2. I need to know the requirements of a Slack bot
3. So that work can be planned and connected components can be evaluated

## Acceptance criteria
A Markdown document containing the following information or estimations as bullet points is created
* requirements
* services required for the implementation and execution
* licence restrictions
* development effort
* other requirements
* comments
* links / sources

## Definition of done (DoD)
* documentation is uploaded in the Documentation folder

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by zenzeii** [comment]
Documentation is uploaded in the Documentation folder:
https://github.com/amosproj/amos2023ss03-qachat/blob/main/Documentation/Slack_Bot_Requirements.md
