### ISSUE TITLE
Test Slack

### ISSUE THREAD

**Issue by SaraElBrak** [amosproj/amos2023ss03-qachat#51]
## User story
1. As a Software Developer
2. I want / need to make sure that the testing environment works well
3. So that the tests are conducted smoothly

## Acceptance criteria
* The test environment should be properly configured.
* The test data used in the testing process should be realistic and representative of the data that will be used in the go-live.
* The test results should be consistent and reliable. 
* Any bugs or defects found during testing should be documented, prioritized, and addressed by the development team.

## Definition of done (DoD)
* Acceptance criteria are met.
* Work products are uploaded to the Github repository.
* A pull request is created for each related branch.
* The work products in the pull requests are reviewed.
* The corresponding branches are merged and closed.
* The bill of materials section of the planning documents is updated.
* All defined conventions are complied with.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by emuguy1** [comment]
Felix and I will do this as part of the creation of a SlackBotFramwework
