### ISSUE TITLE
initialize code repository

### ISSUE THREAD

**Issue by tkonheiser** [amosproj/amos2023ss03-qachat#6]
## User story
1. As a project team
2. We need a structured Code Repository
3. So that we can work effectively and understand the project components

## Acceptance criteria
* first draft of README.md is created
* team logo is added
* coding environment is created (directory structure, .gitignore, ...)
* branch for code development is created

## Definition of done (DoD)
* GitHub code repository meets acceptance criteria

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by emuguy1** [comment]
As a coding environment can only be created after we selected an approach, the rest needs to be done later.

**Comment by emuguy1** [comment]
I decided, that the default branch is the master branch.  For every Ticket/Feature the developer will create its own branch and for integration create a Pull Request. This also means that the Pull Request will only be merged when it works without errors and a second developer approves the code.
