### ISSUE TITLE
create a secure and private file exchange channel

### ISSUE THREAD

**Issue by tkonheiser** [amosproj/amos2023ss03-qachat#65]
## User story
1. As a project team
2. I need a secure and private channel to exchange files
3. So that files that can not be pushed to Github (e.g. env file with tokens, confidential data) be exchanged in an efficient way

## Acceptance criteria
* the options for a secure, private and user friendly file exhange channel are researched and evaluated
* existing files are moved there
* access is set up for all team members

## Definition of done (DoD)
* Acceptance criteria are met.
* Work products are uploaded to the Github repository.
* A pull request is created for each related branch.
* The work products in the pull requests are reviewed.
* The corresponding branches are merged and closed.
* The bill of materials section of the planning documents is updated.
* All defined conventions are complied with.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by zenzeii** [comment]
We decided for a channel and you all should receive an email invitation to the folder from Sync.com
