### ISSUE TITLE
move existing documentation to GitHub Wiki

### ISSUE THREAD

**Issue by tkonheiser** [amosproj/amos2023ss03-qachat#66]
## User story
1. As a project team
2. I want the documentation of the project to be integrated in the GitHub Wiki
3. So that all documentation is in one easy-to-find and well-structured source.

## Acceptance criteria
* the GitHub Wiki contains all created documentation from the Documentation folder
* the GitHub Wiki is divided in user, (technical) design and build / deploy documentation
* moved documentation is deleted from the Documentation folder
* links to the documentation are adjusted  

## Definition of done (DoD)
* Acceptance criteria are met.
* Work products are uploaded to the Github repository.
* A pull request is created for each related branch.
* The work products in the pull requests are reviewed.
* The corresponding branches are merged and closed.
* The bill of materials section of the planning documents is updated.
* All defined conventions are complied with.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by emuguy1** [comment]
Tasks identified:
- [ ] Move existing Documentation
- [ ] Create Custom sidbar
- [ ] Recreate linking
- [ ] Update front Readme
