### ISSUE TITLE
read data from Confluence into vector database

### ISSUE THREAD

**Issue by tkonheiser** [amosproj/amos2023ss03-qachat#76]
## User story
1. As a admin
2. I want / need to read data from Confluence, process the content and store extracted vectors in the vector database
3. So that information from Confluence can be used as part of the Slackbot responses.

## Acceptance criteria
* dummy pages with different contents and structures are created
* functions for Confluence reading, content processing and vector generation are implemented

## Definition of done (DoD)
* Acceptance criteria are met.
* Work products are uploaded to the Github repository.
* A pull request is created for each related branch.
* The work products in the pull requests are reviewed.
* The corresponding branches are merged and closed.
* The bill of materials section of the planning documents is updated.
* All defined conventions are complied with.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by zenzeii** [comment]
Types of data to be read is communicated with Client:

We read:
- content (including attachments/pdfs) of a page from a global space
 
and we exclude:
- any content from personal spaces
- any blog content from any spaces
- any comments from any pages
