### ISSUE TITLE
fix chatbot's inability to respond to multiple users simultaneously

### ISSUE THREAD

**Issue by SaraElBrak** [amosproj/amos2023ss03-qachat#82]
## User story
1. As a software developer
2. I want / need to rewrite the chatbot by implemeting a queue system
3. So that the chatbot can process user requests sequentially, ensuring that each user's request is handled properly without conflicts or concurrency issues.

## Acceptance criteria
* The chatbot should be able to handle multiple users testing it simultaneously without encountering unresponsive behavior.
* User requests must be processed in the order they are received, ensuring fairness and avoiding conflicts.
* Documentation should be updated to reflect the changes made to the chatbot architecture and how the queue system operates.

## Definition of done (DoD)
* Acceptance criteria are met.
* Work products are uploaded to the Github repository.
* A pull request is created for each related branch.
* The work products in the pull requests are reviewed.
* The corresponding branches are merged and closed.
* The bill of materials section of the planning documents is updated.
* All defined conventions are complied with.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by tkonheiser** [comment]
not relevant any more
