### ISSUE TITLE
initialize user, (technical) design, and build/deploy documentation

### ISSUE THREAD

**Issue by SaraElBrak** [amosproj/amos2023ss03-qachat#85]
## User story
1. As a Project Team
2. I want / need to create and set up the necessary documentation supporting the project
3. So that we can ensures a smooth user experience, promote consistency in development, aid knowledge transfer and simplify deployment processes.

## Acceptance criteria
* Create PDFs of the wiki pages and upload them to Deliverables folder
* Name and upload files to _sprint-06/{user|design|build}-documentation.pdf_
* Clarity and Readability : the documentation is written in clear and concise language, making it easily understandable for the intended audience.
* Completeness and Coverage : the documentation covers all essential aspects, including user instructions, technical design, and build/deploy processes in addittion to comprehensive information about the chatbot's features, functionality, and limitations.
* Up-to-date : the documentation provides accurate and updated information that reflects the current state of the chatbot and its functionalities, aligning with the actual implementation and behavior of the chatbot.
* Ease of Navigation and Searchability : the documentation is organized into sections/chapters, allowing users to easily navigate and find relevant information (include a table of contents/index for quick access to specific topics or keywords, links or cross-references).
* Visual aids and examples such as diagrams, screenshots, or illustrations are recommended to support understanding.

## Definition of done (DoD)
* Acceptance criteria are met.
* Work products are uploaded to the Github repository.
* A pull request is created for each related branch.
* The work products in the pull requests are reviewed.
* The corresponding branches are merged and closed.
* The bill of materials section of the planning documents is updated.
* All defined conventions are complied with.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by emuguy1** [comment]
@Tobias Konheiser @سارة  In the acceptance criteriais written that it should be searchable/ navigatable. This is meant for the PDF Documents or the wiki? Im just asking as the wiki is already sorted and linked and I don't really know whether it is useful for the probably very short documents.

**Comment by emuguy1** [comment]
work tasks:

- [ ] In User Documentation add Saction Use the bot
- [ ] Rewrite Deployment Video into Documentation
- [ ] Deployment Documentation add PDF Scraper setup
- [ ] Export Documents as PDFs
- [ ] Add Translation Test Documentation

**Comment by SaraElBrak** [comment]
In this sprints homework (https://docs.google.com/document/d/1ELeRxm30hb7p6sNm3OtpFh6HGTuOhBOW_DTp98vCRQY/edit#), it's mentioned that PDFs of the wiki pages should be created in order to be uploaded in the Deliverables folder. Hence, the PDF and the wiki have actually the same content and the acceptance criteria must be fullfiled in both.
I took a look into the wiki, and it's already well navigatable with the right side menu including all the necessary sections, the 3 required types of documentation and the quick access indexes. Great job ! :)

Please confirm if your question was answered clearly.
