### ISSUE TITLE
setup LLM in the Google cloud

### ISSUE THREAD

**Issue by tkonheiser** [amosproj/amos2023ss03-qachat#93]
## User story
1. As a Project Team
2. I want / need to host the LLM in the Google cloud
3. So that every team member can run the LLM.

## Acceptance criteria
* setup the LLM hosting in the Google cloud
* document the setup process

## Definition of done (DoD)
* Acceptance criteria are met.
* Work products are uploaded to the Github repository.
* A pull request is created for each related branch.
* The work products in the pull requests are reviewed.
* The corresponding branches are merged and closed.
* The bill of materials section of the planning documents is updated.
* All defined conventions are complied with.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by zenzeii** [comment]
Documentation for setup GCP is added here https://github.com/amosproj/amos2023ss03-qachat/wiki/Google-Cloud-Platform-Setup

**Comment by zenzeii** [comment]
Documentation for run and stop GCP is added here https://github.com/amosproj/amos2023ss03-qachat/wiki/Run-Google-Cloud-Platform/
